# name of action              
name: user/-browser-test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ Write-action-for-UI-tests-for-/users ]
  pull_request:
    branches: [ Write-action-for-UI-tests-for-/users ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true
  repository_dispatch: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: nodeJS and npm version
        run: npm -v
      - name: npm init
        run: npm init -y
      - name: install yarn
        run: npm install --global yarn

      - name: Puppeteer Screenshot Action
        # You may pin to the exact commit or the version.
        uses: JonathanTreffler/full-website-screenshot-action@v1.0
        with:
        # The URL you want puppeteer to visit
          url: https://nscstrdevusw2tuecommon.z5.web.core.windows.net/users
        
          destination: https://nscstrdevusw2tuecommon.blob.core.windows.net/screenshots/capture-users-YYYY-mm-DD-HH-MM-SS.png

      #Azure Login 
      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
        with:
          url: https://nscstrdevusw2tuecommon.z5.web.core.windows.net/users